# Generated by Django 4.2.3 on 2023-07-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('mac', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=45))
            ],
            options={
                'db_table': 'leases',
            },
        ),
    ]

