# Generated by Django 4.2.3 on 2023-07-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cablemodems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableModem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=45)),
                ('software_version', models.CharField(max_length=45))
            ],
            options={
                'db_table': 'cm_models',
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='already_queried',
            field=models.BooleanField(default=False),
        ),
    ]
